name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version-file: .node-version
      - uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
      - run: pnpm install
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev-new # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
